### ISSUE TITLE
Another difference option

### ISSUE THREAD

**Issue by truebluepl** [codemeow/doner#9]
I think there could be another difference option.
For example if first value is -2,77 and second is -3, we get value 0 after rounding, but if we round values at first and then calculate difference, we get more appropriate values. I've just compared sprite movement using standard differences and differences calculated in Libre Office Calc. Sprite moves more realistic using second method.

**Comment by codemeow** [comment]
I have tried both approaches, you can see the *note* at the end of the "difference" option in the readme:

```
Note: Be advised, that in this mode the final point of the object could differ from the last value of the non-diff mode! That happens because of the cumulative rounding error. This cannot be solved easily in the code, as some side effects will present:

If to remove the round call - the 39.999 values will become 39 instead of 40. Thus making final point wrong again
If to calc diff between printed values (not the original ones) then the ever-growing function will sometime produce decreasing values. Like in the example above:
```

So we either have wrong final point (which is vital to be exact when it comes to sprites/tiles switching) or the function's derivative will not be only positive or only negative:
```
00,  00,  01,  02,  03,  05,  08,  10  F(x)
   0    1    1    1    2    3    2     F(x)'
      1    0    0    1    1   -1       F(x)"
```

**Comment by truebluepl** [comment]
Hmm... I think there is some misunderstanding :)

Here is LO sheet with values generated using diff option (column A) and rounded values (column B). In the column D are original values (we have 65 values, not 64), and in the column E difference calculated as rounded value minus rounded value. Please also note sum of the differences is 16 (cell E66).
In this case if I use original differences for moving sprite it won't move.

![image](https://github.com/codemeow/doner/assets/68942963/fbca588b-ba01-43dc-bf60-50de6e1571eb)

Diff values generated by:
`doner -m table -e insine -k 16 -w 1 -d`

Original values generated by:
`doner -m table -e insine -k 16 -s 65 -w 1`

So it will be nice have different :) difference option, e.g. -d2, or option used only with -d, like -round before|after.

**Comment by codemeow** [comment]
`round(d2) - round(d1)`? Okay, I got your point. I'll think what I can do. The main problem is that we should calculate the whole thing in fractional type (see https://github.com/codemeow/doner/blob/master/code/util/dnr_util_plot.c#L40 ) and at the moment the difference calculation is applied in the same function (see https://github.com/codemeow/doner/blob/master/code/util/dnr_util_plot.c#L58 ). The rounding and cutting for the desired formatter is applied in the separate functions for each type (see https://github.com/codemeow/doner/blob/master/code/table/func/dnr_nmod_u8.c#L33 for instance). And as the user can apply different formatting for each table type:
```
-f "%hhd" -c "%f" -l "%llu"
```
we cannot rely on the output type, thus required to calculate the derivative with the raw-est and biggest fractional type (in this case - double).

At the moment I have no idea how to implement rounding here without taking into account all the desired output formats beforehand (and probably banning different types for different table parts). I'll think a bit about the solution. 
Probably solution would be :

1. looking at desired formatter types, 
2. banning it if it's different between table parts,
3. checking if the desired type is integer-kind and not float-kind
4. If the type is float leave it as it is at the moment. This will work as intended without >1.0 rounding error at the end
5. If the type is integer then leave everything above https://github.com/codemeow/doner/blob/master/code/util/dnr_util_plot.c#L58 as is, but calculate diff with rounding.  Keep `prev/pprev` as fractional but write `y` result as `round(prev) - round(curr)`

If that is what you imagined I'll try to implement it later.

**Comment by truebluepl** [comment]
Hello!
I think it could be good solution. There should be generated `n+1` values (when `n` is value of `k` parameter) calculated as `round(value)-round(prev_value)`.
In my opinion you could allow for any format and format output values as if they where floats (because they can be treated as floats just without decimal part - because of rounding).

**Comment by truebluepl** [comment]
Hello, any progress? :)

**Comment by codemeow** [comment]
Will do in the near future. Had some personal issues, sorry.

**Comment by codemeow** [comment]
Please, check if the new version is ok: https://github.com/codemeow/doner/releases/tag/v1.2
```
$ ./doner -m table -e insine -k 16 -s 65 -w 65 -f " %d " -c "%d " -l "%d" -d
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0
```

```
$ ./doner -m table -e insine -k 16 -s 65 -w 20 -f " %5.2f " -c "%5.2f " -l "%5.2f"
  0.00  0.00  0.02  0.04  0.08  0.12  0.17  0.24  0.31  0.39  0.48  0.58  0.69  0.81  0.94  1.07  1.22  1.37  1.54  1.71
  1.89  2.08  2.28  2.48  2.70  2.92  3.15  3.39  3.63  3.88  4.14  4.41  4.69  4.97  5.26  5.55  5.85  6.16  6.47  6.79
  7.11  7.44  7.77  8.11  8.46  8.81  9.16  9.52  9.88 10.24 10.61 10.98 11.36 11.73 12.11 12.49 12.88 13.26 13.65 14.04
 14.43 14.82 15.21 15.61 16.00 
```

```
$ ./doner -m table -e insine -k 16 -s 65 -w 20 -f " %5.2f " -c "%5.2f " -l "%5.2f" -d
  0.00  0.00  0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.10  0.11  0.12  0.13  0.14  0.15  0.15  0.16  0.17
  0.18  0.19  0.20  0.21  0.21  0.22  0.23  0.24  0.25  0.25  0.26  0.27  0.27  0.28  0.29  0.29  0.30  0.31  0.31  0.32
  0.32  0.33  0.33  0.34  0.34  0.35  0.35  0.36  0.36  0.36  0.37  0.37  0.37  0.38  0.38  0.38  0.38  0.39  0.39  0.39
  0.39  0.39  0.39  0.39  0.39 
```

**Comment by truebluepl** [comment]
Hello!
Hmm....I think I get the same values as in previous versions.
`doner.exe -m table -e insine -k 16 -w 1 -d`
I would like get values like in the column E of my LO screenshot.

**Comment by codemeow** [comment]
By default the formatter is "%f". You need to excplicitly say which format you'd like:
```
$ ./doner -m table -e insine -k 16 -w 1 -d -f "%d " -c "%d " -l "%d" -w 16
0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1
0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0
```
```
-f "%d " -c "%d " -l "%d"
```

**Comment by truebluepl** [comment]
Yes! Thank you very much. This is exactly want I need:)
